name: Update Mirror

on:
  push:
    branches:
      - main

jobs:
  push_to_epitech_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Push to Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_KEY }}

      - name: Display the mirror repository name
        run: echo "::notice::Code has been pushed to ${{ vars.REPO_URL }}"
